In [42]:
import torch
import numpy as np
from torch.autograd import Variable

# create Tensor
a = torch.Tensor([[2,3],[4,8],[7,9]])

print('a is :{}'.format(a))

print('a size is {}'.format(a.size()))
print('a[2,1] is {}'.format(a[2,1]))
a[2,1] = 100
print('changed a is {}'.format(a))

a is :tensor([[2., 3.],
        [4., 8.],
        [7., 9.]])
a size is torch.Size([3, 2])
a[2,1] is 9.0
changed a is tensor([[  2.,   3.],
        [  4.,   8.],
        [  7., 100.]])


In [40]:
# create different format of Tensor
b = torch.LongTensor([[2,3],[4,8],[7,9]])
print('a is \n {}'.format(a))
print('b size is {}'.format(b.size()))
numpy_b = b.numpy
print('conver to numpy is \n {}'.format(b))

a is 
 tensor([[  2.,   3.],
        [  4.,   8.],
        [  7., 100.]])
b size is torch.Size([3, 2])
conver to numpy is 
 tensor([[2, 3],
        [4, 8],
        [7, 9]])


In [26]:
c = torch.zeros((3,2)) 
# c = torch.zeros(3,2)  # two lines of codes have the same results of variable c's print
print('c is {}'.format(c))

c is tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [27]:
# d = torch.randn(3,2)
d = torch.randn((3,2)) # two lines of codes have the same results of variable d's print
print('d is {}'.format(d))

d is tensor([[ 0.5601,  0.8366],
        [ 0.6500, -0.9234],
        [ 0.6579, -1.0546]])


In [39]:
e = np.array([[2,3],[4,5]])
torch_e = torch.from_numpy(e)
print('from numpy to tensor is \n {}'.format(torch_e))
f_torch_e = torch_e.float()
print('change data type to float e is \n {}'.format(f_torch_e))

from numpy to tensor is 
 tensor([[2, 3],
        [4, 5]])
change data type to float e is 
 tensor([[2., 3.],
        [4., 5.]])


In [46]:
# Section 3.1.2 Variable:

# create variable
x = Variable(torch.Tensor([1]), requires_grad=True)
w = Variable(torch.Tensor([2]), requires_grad=True)
b = Variable(torch.Tensor([3]), requires_grad=True)

# build a computional graph
y = w*x+b

# compute gradients
y.backward()
# print out the gradients
print(x.grad)
print(w.grad)
print(b.grad)

tensor([2.])
tensor([1.])
tensor([1.])


In [54]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x*2
print(y)

y.backward(torch.FloatTensor([1, .1, .01]))
print(x.grad)

tensor([ 1.1647,  1.5499, -2.8367], grad_fn=<MulBackward0>)
tensor([2.0000, 0.2000, 0.0200])


In [1]:
# class myDataset(Dataset): 
#     def __init__(self, csv_file, txt_file, root_dir, other_file) :
#         self.csv_data = pd.read_csv(csv_file)
#         with open(txt_file, 'r') as f:
#             data_list = f.readlines()
        